apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: podsimpleproject
      labels:
        app: web
    spec:
      containers:
        - name: site
          image: matheusmprado/simpleproject:lts
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30000
  type: NodePort
